notifications:
  email:
    on_success: never
    on_failure: never

language: php
php:
  - 7.0
  - 5.6
  - 5.5



before_script:
    - wget https://scrutinizer-ci.com/ocular.phar

    # Composer
    - composer validate
    - composer update


script: 
    - php --version
    - composer --version
    - phpunit --version

    - phpunit --bootstrap test/config.php --coverage-clover coverage.clover test



after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
